server:
  port: 9000
  servlet:
    session:
      cookie:
        max-age: 5s
logging:
#  level:
#    root: debug
#    org:
#      hibernate: debug
spring:
  #  autoconfigure:
  #    exclude:
#  security:
#      user:
#        name: a
#        password: a
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
  profiles:
    active: prod
---
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  config:
    activate:
      on-profile: dev
---
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: welcome
